version: '3.3'
services:
    turret:
        devices:
            - /dev/snd
        environment:
            - AUDIO_GRP=$(getent group audio | cut -d":" -f3)
            - XDG=$(XDG_RUNTIME_DIR)
            - 'PULSE_SERVER=unix:$(XDG)/pulse/native'
        volumes:
            - '$(XDG)/pulse/native:$(XDG)/pulse/native'
            - '~/.config/pulse/cookie:/root/.config/pulse/cookie'
        group_add: 
            - $(AUDIO_GRP)
        image: 'turret:latest'


#docker run \
#--device /dev/snd \
#-e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
#-v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
#-v ~/.config/pulse/cookie:/root/.config/pulse/cookie \
#--group-add $(getent group audio | cut -d: -f3) \
#audio:test$(getent group audio | cut -d: -f3)